/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servicios' | '/sobre-nosotros' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servicios' | '/sobre-nosotros' | '/api/chat'
  id: '__root__' | '/' | '/servicios' | '/sobre-nosotros' | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiciosRoute: ServiciosRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
