// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function isNewSupabaseApiKey(value?: string): boolean {
  if (!value) return false;
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'] || 'https://gsjgylomutnburmzrmmd.supabase.co';
    const SUPABASE_PUBLISHABLE_KEY = process.env['VITE_SUPABASE_ANON_KEY'] || process.env['SUPABASE_ANON_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'] || 'sb_publishable_BE3OnBe-y_k_QNuYy2eDsw_9NH1KuPE';
    
    const request = getRequest();
    const authHeader = request?.headers?.get('authorization') || '';
    const token = authHeader.startsWith('Bearer ') ? authHeader.replace('Bearer ', '') : '';

    // Si la petición no lleva un token válido (como al visitar la web directamente), no rompemos el servidor con 500
    if (!token || token.split('.').length !== 3) {
      return next({
        context: {
          supabase: createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY),
          userId: null,
          claims: null,
        },
      });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    try {
      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims || !data.claims.sub) {
        return next({
          context: {
            supabase,
            userId: null,
            claims: null,
          },
        });
      }

      return next({
        context: {
          supabase,
          userId: data.claims.sub,
          claims: data.claims,
        },
      });
    } catch {
      return next({
        context: {
          supabase,
          userId: null,
          claims: null,
        },
      });
    }
  },
);
